settings = {
    "finishline.job-runner.sh": "job-runner.cached.sh",
    "finishline.sqlalchemy.engine.uri": "sqlite:///finishline.db",
    "finishline.sqlalchemy.engine.echo": False,
    "finishline.job.name.ignored":["job-runner total-status", "imports", "exports", "reports"],
    "finishline.job.name.meta": ["job-runner version-info", "job-runner enabled-jobs"],
    "finishline.job.name": "job",
    "finishline.job.status": "job-status",
    "finishline.job.status.starting": "starting",
    "finishline.job.status.success": "success",
    "finishline.job.status.failure": "failed",
    "finishline.job.timestamp": "time",
    "finishline.job.date": "date",
    "finishline.job.timestamp.format": "%Y-%m-%dT%H:%M:%S %z",
    "finishline.job.date.format": "%Y-%m-%d",
}
